var searchData=
[
  ['readme',['README',['../md__g_1__libraries__demgel_8_redis__r_e_a_d_m_e.html',1,'']]],
  ['read',['Read',['../interface_demgel_redis_1_1_interfaces_1_1_i_redis_handler.html#a04550ae73923a29c2709850a7b299d94',1,'DemgelRedis.Interfaces.IRedisHandler.Read()'],['../class_demgel_redis_1_1_object_manager_1_1_handlers_1_1_enumerable_handler.html#a6b84b56dda376ce7ecdb2a543a7c0ecc',1,'DemgelRedis.ObjectManager.Handlers.EnumerableHandler.Read()'],['../class_demgel_redis_1_1_object_manager_1_1_handlers_1_1_redis_handler.html#a094629bfc66d785f22295cf406917214',1,'DemgelRedis.ObjectManager.Handlers.RedisHandler.Read()']]],
  ['readme_2emd',['README.MD',['../_r_e_a_d_m_e_8_m_d.html',1,'']]],
  ['redishandler',['RedisHandler',['../class_demgel_redis_1_1_object_manager_1_1_handlers_1_1_redis_handler.html',1,'DemgelRedis::ObjectManager::Handlers']]],
  ['redishandler',['RedisHandler',['../class_demgel_redis_1_1_object_manager_1_1_handlers_1_1_redis_handler.html#ac589e0333db79219fd985f02d382bd9f',1,'DemgelRedis::ObjectManager::Handlers::RedisHandler']]],
  ['redishandler_2ecs',['RedisHandler.cs',['../_redis_handler_8cs.html',1,'']]],
  ['redisidkey',['RedisIdKey',['../class_demgel_redis_1_1_object_manager_1_1_attributes_1_1_redis_id_key.html',1,'DemgelRedis::ObjectManager::Attributes']]],
  ['redisidkey_2ecs',['RedisIdKey.cs',['../_redis_id_key_8cs.html',1,'']]],
  ['redisjobqueue',['RedisJobQueue',['../class_demgel_redis_1_1_job_queue_1_1_redis_job_queue.html#a9d971219276f17816d0cbccacd360695',1,'DemgelRedis::JobQueue::RedisJobQueue']]],
  ['redisjobqueue',['RedisJobQueue',['../class_demgel_redis_1_1_job_queue_1_1_redis_job_queue.html',1,'DemgelRedis::JobQueue']]],
  ['redisjobqueue_2ecs',['RedisJobQueue.cs',['../_redis_job_queue_8cs.html',1,'']]],
  ['rediskey',['RedisKey',['../class_demgel_redis_1_1_common_1_1_redis_key_object.html#ad94d27558ce57f123e6441745b0238ff',1,'DemgelRedis::Common::RedisKeyObject']]],
  ['rediskeyobject',['RedisKeyObject',['../class_demgel_redis_1_1_common_1_1_redis_key_object.html',1,'DemgelRedis::Common']]],
  ['rediskeyobject',['RedisKeyObject',['../class_demgel_redis_1_1_common_1_1_redis_key_object.html#a51572d95a78df61c181ba084934ffbc1',1,'DemgelRedis.Common.RedisKeyObject.RedisKeyObject(IEnumerable&lt; Attribute &gt; attributes, string id)'],['../class_demgel_redis_1_1_common_1_1_redis_key_object.html#a953a8d79b7522ed7c83b048921bc7f7b',1,'DemgelRedis.Common.RedisKeyObject.RedisKeyObject()']]],
  ['rediskeyobject_2ecs',['RedisKeyObject.cs',['../_redis_key_object_8cs.html',1,'']]],
  ['redisnoautosave',['RedisNoAutoSave',['../class_demgel_redis_1_1_object_manager_1_1_attributes_1_1_redis_no_auto_save.html',1,'DemgelRedis::ObjectManager::Attributes']]],
  ['redisnoautosave_2ecs',['RedisNoAutoSave.cs',['../_redis_no_auto_save_8cs.html',1,'']]],
  ['redisobjectmanager',['RedisObjectManager',['../class_demgel_redis_1_1_object_manager_1_1_redis_object_manager.html',1,'DemgelRedis::ObjectManager']]],
  ['redisobjectmanager',['RedisObjectManager',['../class_demgel_redis_1_1_object_manager_1_1_redis_object_manager.html#ae033645a4f3cfccde846e71dc115fb02',1,'DemgelRedis.ObjectManager.RedisObjectManager.RedisObjectManager()'],['../class_demgel_redis_1_1_object_manager_1_1_redis_object_manager.html#aed91c882241ecfe5022328f1366f71ad',1,'DemgelRedis.ObjectManager.RedisObjectManager.RedisObjectManager(IRedisBackup redisBackup)']]],
  ['redisobjectmanager_2ecs',['RedisObjectManager.cs',['../_redis_object_manager_8cs.html',1,'']]],
  ['redisprefix',['RedisPrefix',['../class_demgel_redis_1_1_object_manager_1_1_attributes_1_1_redis_prefix.html',1,'DemgelRedis::ObjectManager::Attributes']]],
  ['redisprefix_2ecs',['RedisPrefix.cs',['../_redis_prefix_8cs.html',1,'']]],
  ['redissuffix',['RedisSuffix',['../class_demgel_redis_1_1_object_manager_1_1_attributes_1_1_redis_suffix.html',1,'DemgelRedis::ObjectManager::Attributes']]],
  ['redissuffix_2ecs',['RedisSuffix.cs',['../_redis_suffix_8cs.html',1,'']]],
  ['redisvaluedictionary',['RedisValueDictionary',['../class_demgel_redis_1_1_job_queue_1_1_redis_value_dictionary.html',1,'DemgelRedis::JobQueue']]],
  ['redisvaluedictionary_2ecs',['RedisValueDictionary.cs',['../_redis_value_dictionary_8cs.html',1,'']]],
  ['redisvalueextensions_2ecs',['RedisValueExtensions.cs',['../_redis_value_extensions_8cs.html',1,'']]],
  ['restorehash',['RestoreHash',['../class_demgel_redis_1_1_backing_manager_1_1_table_redis_backup.html#a07d3687007574e626d1849842b38c036',1,'DemgelRedis.BackingManager.TableRedisBackup.RestoreHash()'],['../interface_demgel_redis_1_1_interfaces_1_1_i_redis_backup.html#aa0a6644c11ee64b23000d0264142612a',1,'DemgelRedis.Interfaces.IRedisBackup.RestoreHash()']]],
  ['restorestring',['RestoreString',['../class_demgel_redis_1_1_backing_manager_1_1_table_redis_backup.html#a24333973d03cd2e2b8777f595a7e6470',1,'DemgelRedis.BackingManager.TableRedisBackup.RestoreString()'],['../interface_demgel_redis_1_1_interfaces_1_1_i_redis_backup.html#a3ee680936017e9acfe1694ba2646e6ac',1,'DemgelRedis.Interfaces.IRedisBackup.RestoreString()']]],
  ['result',['Result',['../class_demgel_redis_1_1_object_manager_1_1_demgel_redis_result.html#acdf1a3b0c2f70c971b1d600f24b1128d',1,'DemgelRedis::ObjectManager::DemgelRedisResult']]],
  ['retrieveobjectproxy_3c_20t_20_3e',['RetrieveObjectProxy&lt; T &gt;',['../class_demgel_redis_1_1_object_manager_1_1_redis_object_manager.html#a877ed59f8186f98b0ab6629bb541e770',1,'DemgelRedis::ObjectManager::RedisObjectManager']]]
];
